spring:
  application:
    name: jobrunr-spring-batch
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch
    username: batch-user
    password: batch-password
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  sql:
    init:
      mode: always

jobrunr:
  background-job-server:
    enabled: true
    poll-interval-in-seconds: 5
  dashboard:
    enabled: true
